version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: python:3.11-slim
    volumes:
      - ./fontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: python -m http.server 3000