# Generated by Django 4.2.7 on 2026-05-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationimage",
            name="generation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_images",
                to="generation.generation",
            ),
        ),
        migrations.AlterField(
            model_name="generationimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="generated_images/"
            ),
        ),
    ]
