# Generated by Django 4.2.7 on 2026-05-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
