# Generated by Django 4.2.7 on 2026-04-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsdata",
            name="generation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="generation.generation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analyticsdata",
            unique_together={("generation", "date")},
        ),
    ]
